### ISSUE TITLE
Can you help me ?

### ISSUE THREAD

**Issue by ggvans** [tpmmthomas/binance-copy-trade-bot#1]
Hello excuse me to disturb you, I am new to this field and I have been trying to set up this robot for 2 days now. Unfortunately I am stuck on these data to enter:
auth_code = ""  # set it yourself
admin_code = ""  # set it yourself
Where can I find this?

**Comment by tpmmthomas** [comment]
Hi. This is supposed to be a value that you decide set for yourself, which protects your bot from unauthorized access (like a password)
