### ISSUE TITLE
I have a problem to start a bot

### ISSUE THREAD

**Issue by VilkinsYT** [tpmmthomas/binance-copy-trade-bot#12]
I have a bot a problem to start a bot on windows.
If you can help me please you can contact me on discord : Vilkins#5491

**Comment by tpmmthomas** [comment]
Sorry I won't help with individual technical problems. If you have a very specific problem or bug encountered you can raise here.

**Comment by tpmmthomas** [comment]
The bot is developed in linux too, it is recommended to use a linux environment to run.

**Comment by VilkinsYT** [comment]
Ok thank you and if i use linux Debian 11 is good for the bot?

**Comment by tpmmthomas** [comment]
It should be fine. For your reference my environment is Ubuntu20.04.
