### ISSUE TITLE
How to easily perform copy trading for a beginner?

### ISSUE THREAD

**Issue by PowerGrb** [tpmmthomas/binance-copy-trade-bot#16]
Hello, I am new to programming. I would like to be able to run your script easily. Is it possible or do I need to have better knowledge? I see several files and I don't know which one to run for copy trading. Are they all nested together? When I go to Visual Sutdio Code and run a random file they tell me that the "app" module is missing. I already have my Bybit API keys but I don't know where to enter them. I installed all required extensions. Thank you in advance for a possible comprehensive answer :)

**Comment by tpmmthomas** [comment]
You need to have some computer programming knowledge. This project is meant to let people set up their own servers and host the copy trade bot service by their own. If you only want to use it without the hassle of setting it up and maintaining servers, you need to find someone who is willing to do it for you.

**Comment by PowerGrb** [comment]
Alright, thank you for your response.
