### ISSUE TITLE
Issue with the proportion parameter

### ISSUE THREAD

**Issue by djayb** [tpmmthomas/binance-copy-trade-bot#3]
Hey there,
Thanks for your work on it bot.
I have tried successfully the follow/alert part, and I am now trying out the copy trading feature.
I have a question regarding the "proportion" parameter which is a bit unclear to me on how it works to define de size of the position, it would be great if you could provide an example.
Also, the commands to update this parameter (/updateall and /updateproportion) doesn't seem to be implemented in the code of the bot, so I'm not sure how to make it work?
Thanks for you help!

**Comment by tpmmthomas** [comment]
Example: if the trader opens 1 BTC and you set the proportion to 0.01, then you will open 0.01 BTC of trades.

I am sorry that the telegram endpoints seems to be incorrect. I have just updated the file.

**Comment by djayb** [comment]
Thanks, with your updated files I was able to update the proportion parameter, so far so good.
